// src/resources/js/svelte/DarkmodeToggle.svelte
<script>
    import { onDestroy, onMount } from 'svelte'

    export let defaultMode = 'system'
    export let storageKey = 'theme'
    export let persistUrl = ''
    export let persistMethod = 'PUT'
    export let persistField = 'dark_mode'
    export let className = 'dark'
    export let dataAttribute = ''
    export let colorScheme = false
    export let toggleLabel = 'Toggle theme'
    export let labels = { light: 'Light', dark: 'Dark', system: 'System' }

    const modes = ['light', 'dark', 'system']

    let open = false
    let current = defaultMode
    let query = null

    function read() {
        try {
            return localStorage.getItem(storageKey)
        } catch (error) {
            return null
        }
    }

    function apply(mode) {
        const isDark = mode === 'dark' || (mode === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches)

        document.documentElement.classList.toggle(className, isDark)

        if (dataAttribute) {
            document.documentElement.setAttribute(dataAttribute, isDark ? 'dark' : 'light')
        }

        if (colorScheme) {
            document.documentElement.style.colorScheme = isDark ? 'dark' : 'light'
        }
    }

    function setTheme(mode) {
        current = mode

        try {
            localStorage.setItem(storageKey, mode)
        } catch (error) {
            // Storage can be unavailable in private windows, the theme still applies.
        }

        apply(mode)
        open = false

        if (persistUrl) {
            fetch(persistUrl, {
                method: persistMethod,
                credentials: 'same-origin',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRF-TOKEN': document.querySelector('meta[name=csrf-token]')?.content,
                    'Accept': 'application/json',
                },
                body: JSON.stringify({ [persistField]: mode }),
            }).catch(() => {})
        }
    }

    function onSystemChange() {
        if (current === 'system') {
            apply('system')
        }
    }

    onMount(() => {
        current = read() || defaultMode
        apply(current)

        query = window.matchMedia('(prefers-color-scheme: dark)')
        query.addEventListener('change', onSystemChange)
    })

    onDestroy(() => {
        query?.removeEventListener('change', onSystemChange)
    })

    function clickOutside(node) {
        const handler = event => {
            if (!node.contains(event.target)) {
                open = false
            }
        }

        document.addEventListener('click', handler, true)

        return {
            destroy() {
                document.removeEventListener('click', handler, true)
            },
        }
    }
</script>

<svelte:window on:keydown={event => event.key === 'Escape' && (open = false)} />

<div class="relative" use:clickOutside>
    <button
        type="button"
        aria-expanded={open}
        aria-haspopup="true"
        aria-label={toggleLabel}
        title={toggleLabel}
        on:click={() => open = !open}
    >
        {#if current === 'light'}
            <svg class="h-5 w-5" aria-hidden="true" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" /></svg>
        {:else if current === 'dark'}
            <svg class="h-5 w-5" aria-hidden="true" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" /></svg>
        {:else}
            <svg class="h-5 w-5" aria-hidden="true" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" /></svg>
        {/if}
    </button>

    {#if open}
        <div role="menu" class="absolute right-0 mt-1 w-36 rounded-lg bg-white dark:bg-gray-800 shadow-lg z-50">
            {#each modes as mode}
                <button
                    type="button"
                    role="menuitemradio"
                    aria-checked={current === mode}
                    class="block w-full px-4 py-2 text-sm text-left {current === mode ? 'font-bold' : ''}"
                    on:click={() => setTheme(mode)}
                >{labels[mode]}</button>
            {/each}
        </div>
    {/if}
</div>

// src/resources/js/vue/DarkmodeToggle.vue
<script setup>
import { onBeforeUnmount, onMounted, ref } from 'vue'

const props = defineProps({
    defaultMode: { type: String, default: 'system' },
    storageKey: { type: String, default: 'theme' },
    persistUrl: { type: String, default: '' },
    persistMethod: { type: String, default: 'PUT' },
    persistField: { type: String, default: 'dark_mode' },
    className: { type: String, default: 'dark' },
    dataAttribute: { type: String, default: '' },
    colorScheme: { type: Boolean, default: false },
    toggleLabel: { type: String, default: 'Toggle theme' },
    labels: {
        type: Object,
        default: () => ({ light: 'Light', dark: 'Dark', system: 'System' }),
    },
})

const modes = ['light', 'dark', 'system']
const open = ref(false)
const current = ref(props.defaultMode)
const root = ref(null)

let query = null

function read() {
    try {
        return localStorage.getItem(props.storageKey)
    } catch (error) {
        return null
    }
}

function apply(mode) {
    const isDark = mode === 'dark' || (mode === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches)

    document.documentElement.classList.toggle(props.className, isDark)

    if (props.dataAttribute) {
        document.documentElement.setAttribute(props.dataAttribute, isDark ? 'dark' : 'light')
    }

    if (props.colorScheme) {
        document.documentElement.style.colorScheme = isDark ? 'dark' : 'light'
    }
}

function setTheme(mode) {
    current.value = mode

    try {
        localStorage.setItem(props.storageKey, mode)
    } catch (error) {
        // Storage can be unavailable in private windows, the theme still applies.
    }

    apply(mode)
    open.value = false

    if (props.persistUrl) {
        fetch(props.persistUrl, {
            method: props.persistMethod,
            credentials: 'same-origin',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRF-TOKEN': document.querySelector('meta[name=csrf-token]')?.content,
                'Accept': 'application/json',
            },
            body: JSON.stringify({ [props.persistField]: mode }),
        }).catch(() => {})
    }
}

function onSystemChange() {
    if (current.value === 'system') {
        apply('system')
    }
}

function onDocumentClick(event) {
    if (root.value && !root.value.contains(event.target)) {
        open.value = false
    }
}

onMounted(() => {
    current.value = read() || props.defaultMode
    apply(current.value)

    query = window.matchMedia('(prefers-color-scheme: dark)')
    query.addEventListener('change', onSystemChange)
    document.addEventListener('click', onDocumentClick)
})

onBeforeUnmount(() => {
    query?.removeEventListener('change', onSystemChange)
    document.removeEventListener('click', onDocumentClick)
})
</script>

<template>
    <div ref="root" class="relative" @keydown.escape="open = false">
        <button
            type="button"
            :aria-expanded="open"
            aria-haspopup="true"
            :aria-label="toggleLabel"
            :title="toggleLabel"
            @click="open = !open"
        >
            <svg v-if="current === 'light'" class="h-5 w-5" aria-hidden="true" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" /></svg>
            <svg v-else-if="current === 'dark'" class="h-5 w-5" aria-hidden="true" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" /></svg>
            <svg v-else class="h-5 w-5" aria-hidden="true" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" /></svg>
        </button>

        <div v-if="open" role="menu" class="absolute right-0 mt-1 w-36 rounded-lg bg-white dark:bg-gray-800 shadow-lg z-50">
            <button
                v-for="mode in modes"
                :key="mode"
                type="button"
                role="menuitemradio"
                :aria-checked="current === mode"
                class="block w-full px-4 py-2 text-sm text-left"
                :class="current === mode ? 'font-bold' : ''"
                @click="setTheme(mode)"
            >
                {{ labels[mode] }}
            </button>
        </div>
    </div>
</template>
